import Head from "next/head";
import { Case } from "../../components/case/case";

export default function Page() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Case
        pt="80px"
        bgColor="#004F9F"
        project="OPADE"
        services={[
          "Product Strategy",
          "Product Design",
          "Product Development",
          "Hosting",
        ]}
        client="K.I.T. Group"
        sector="Event Management / SaaS"
      />
    </>
  );
}
